services:
  - type: web
    name: studypulse-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn studypulse_project.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: WEB_CONCURRENCY
        value: 4
      - key: SECRET_KEY
        value: 8rzhh91!w=bz4)wpjud-370#r=qrbgf-up2t9)11fur8(84a18
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://studypulse.vercel.app
      - key: DATABASE_URL
        value: postgresql://studypulse_user:U1msR1v4GyitWcvctKM73C2nXI2xPOrx@dpg-d35r6e8dl3ps73966d70-a/studypulse_g2ni