# Generated by Django 5.0 on 2025-04-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_course_module_lesson_userprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='content',
        ),
        migrations.AddField(
            model_name='lesson',
            name='external_url',
            field=models.URLField(blank=True, help_text='URL for external resources.', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='text_content',
            field=models.TextField(blank=True, help_text='Content for text lessons.', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='xp_value',
            field=models.PositiveIntegerField(default=10, help_text='XP awarded for completing this lesson'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='youtube_video_id',
            field=models.CharField(blank=True, help_text='Only the YouTube video ID (e.g., dQw4w9WgXcQ)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text Content'), ('youtube', 'YouTube Video'), ('external_link', 'External Link')], default='text', max_length=20),
        ),
    ]
